// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpztsglyjzofglvkosfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwenRzZ2x5anpvZmdsdmtvc2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTYxMzQsImV4cCI6MjA3MDU3MjEzNH0.OScG_2cWRJFIhqDwFCNSkN7CLN0KJuMPxYd33ntshbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});